package web

const (
	html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>问答版搜索 - {{.Name}}</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/xmdhs/searchqanda/style.css"></head><body><div class="container-lg px-3 my-5 markdown-body"><h1>{{.Name}}</h1>{{range .List}}<h3><a href="{{ .Link}}" target="_blank">{{ .Title}}</a></h3><blockquote><p>{{ .Txt}}{{if .Key}}<font color="red">{{ .Key}}</font>{{ .Txt1}}{{end}}</p></blockquote>{{end}} {{if .T}}<br><hr><p><a href="{{ .Link}}">more</a></p>{{else}} {{end}}</div><script src="https://cdn.jsdelivr.net/npm/anchor-js/anchor.min.js"></script><script>anchors.add();</script></body></html>`

	index = `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>问答版搜索</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/xmdhs/searchqanda/style.css"></head><body><div class="container-lg px-3 my-5 markdown-body"><h1>问答版搜索</h1><form action="/search/s" target="_blank"><input type="text" name="q"></form><br><hr><details><summary>用法说明</summary><p>使用空格分隔关键词。例如 <code class="language-plaintext highlighter-rouge">崩溃 log</code>，表示搜索结果中必须有“崩溃”和“log”。</p><p>关键词前加 <code class="language-plaintext highlighter-rouge">-</code> 表示搜索结果中不能含有此关键词。例如 <code class="language-plaintext highlighter-rouge">崩溃 -log</code>，表示搜索结果中必须有 “崩溃”，必须没有 "log"。</p><p>关键词使用 <code class="language-plaintext highlighter-rouge">""</code> 围住表示忽略空格的作用。例如 <code class="language-plaintext highlighter-rouge">"崩溃 log"</code>，表示搜索结果中必须有 <code class="language-plaintext highlighter-rouge">崩溃 log</code> 或者 <code class="language-plaintext highlighter-rouge">崩溃log</code> 不能有 <code class="language-plaintext highlighter-rouge">log 崩溃</code>。</p></details></div><script src="https://cdn.jsdelivr.net/npm/anchor-js/anchor.min.js"></script><script>anchors.add();</script></body></html>`

	snapshot = `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>问答版搜索 - 快照</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/xmdhs/searchqanda/style.css"></head><body><div class="container-lg px-3 my-5 markdown-body"><h1>快照</h1><form action="/search/snapshot" target="_blank"><input type="text" name="q"></form></div><script src="https://cdn.jsdelivr.net/npm/anchor-js/anchor.min.js"></script><script>anchors.add();</script></body></html>`
)
